# Generated by Django 6.0.3 on 2026-06-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee')},
        ),
    ]
