# Generated by Django 6.0.3 on 2026-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
